// Build dist/kachaka-ltc-demo.html: one self-contained file (JS, CSS and fonts inlined)
// that plays offline, even when opened straight from disk with a double-click.
// usage: npm install && npm run build:offline
import { build } from "esbuild";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const src = path.join(root, "src");
const out = path.join(root, "dist", "kachaka-ltc-demo.html");

// "three" and "three/addons/*" resolve to the vendored copy, same as the page's import map
const vendoredThree = {
  name: "vendored-three",
  setup(b) {
    b.onResolve({ filter: /^three$/ }, () => ({ path: path.join(src, "vendor/three/three.module.min.js") }));
    b.onResolve({ filter: /^three\/addons\// }, (args) => ({
      path: path.join(src, "vendor/three/addons", args.path.slice("three/addons/".length)),
    }));
  },
};

const bundle = await build({
  entryPoints: [path.join(src, "js/phase_3/main.js")],
  bundle: true,
  format: "esm",
  target: "es2022",
  minify: true,
  legalComments: "eof",
  write: false,
  plugins: [vendoredThree],
});
const js = bundle.outputFiles[0].text.replace(/<\/script/gi, "<\\/script");

// inline the woff2 files referenced by the stylesheet
let css = await readFile(path.join(src, "css/hospital-styles.css"), "utf8");
const fonts = [...css.matchAll(/url\("(\.\.\/assets\/fonts\/[^"]+\.woff2)"\)/g)];
for (const [, rel] of fonts) {
  const data = await readFile(path.join(src, "css", rel));
  css = css.replace(`url("${rel}")`, `url("data:font/woff2;base64,${data.toString("base64")}")`);
}

let html = await readFile(path.join(src, "phase3_scene.html"), "utf8");
const swap = (from, to) => {
  if (!html.includes(from)) throw new Error(`build_offline: missing ${from}`);
  html = html.replace(from, () => to);
};
swap('<link rel="stylesheet" href="css/hospital-styles.css" />', `<style>\n${css}\n</style>`);
html = html.replace(/\s*<script type="importmap">[\s\S]*?<\/script>/, "");
swap('<script type="module" src="js/phase_3/main.js"></script>', `<script type="module">\n${js}\n</script>`);
html = html.replace("<!DOCTYPE html>", "<!DOCTYPE html>\n<!-- Generated by tools/build_offline.mjs from src/phase3_scene.html - do not edit by hand. -->");

await mkdir(path.dirname(out), { recursive: true });
await writeFile(out, html);
console.log(`wrote ${path.relative(root, out)} (${(html.length / 1024 / 1024).toFixed(2)} MB, ${fonts.length} fonts inlined)`);
