"""Convert Kachaka binary STL meshes (pf-robotics/kachaka-api, Apache-2.0)
into a compact ES module: quantized int16 positions + uint16 indices, base64.

usage: python3 tools/kachaka_stl_to_js.py \
         <kachaka-api>/ros2/kachaka_description/meshes/kachaka \
         src/js/phase_3/kachakaMeshData.js

Coordinates: URDF visual origins are applied in the ROS frame (x fwd, y left,
z up), then converted to three.js (x fwd, y up, z right) via (x, z, -y).
"""
import base64, struct, sys, json
import numpy as np

SRC = sys.argv[1]
OUT = sys.argv[2]

# name -> (file, ROS-frame offset applied to every vertex)
PARTS = {
    "body": ("body.stl", (-0.150, -0.120, 0.0)),        # <visual><origin xyz="-0.150 -0.120 0.0"/>
    "leftTire": ("left_tire.stl", (0.0, 0.0, 0.0)),     # joint at (0,  0.100, 0.045)
    "rightTire": ("right_tire.stl", (0.0, 0.0, 0.0)),   # joint at (0, -0.100, 0.045)
    "solenoid": ("solenoid.stl", (0.0, 0.0, 0.0)),      # docking pin, prismatic 0..0.012 m
}


def read_stl(path):
    with open(path, "rb") as f:
        data = f.read()
    n = struct.unpack("<I", data[80:84])[0]
    assert 84 + 50 * n == len(data), path
    dt = np.dtype([("n", "<f4", 3), ("v", "<f4", (3, 3)), ("attr", "<u2")])
    return np.frombuffer(data, dtype=dt, count=n, offset=84)["v"].astype(np.float64)


def b64(a):
    return base64.b64encode(a.tobytes()).decode("ascii")


parts = {}
for name, (fname, off) in PARTS.items():
    tris = read_stl(f"{SRC}/{fname}") + np.array(off)
    ros = tris.reshape(-1, 3)
    three = np.stack([ros[:, 0], ros[:, 2], -ros[:, 1]], axis=1)
    lo, hi = three.min(0), three.max(0)
    span = np.where(hi - lo > 0, hi - lo, 1.0)
    q = np.round((three - lo) / span * 65535.0).astype(np.int64) - 32768
    q = q.astype(np.int16)
    uniq, inverse = np.unique(q, axis=0, return_inverse=True)
    inverse = inverse.reshape(-1)
    # drop triangles collapsed by quantization
    tri_idx = inverse.reshape(-1, 3)
    keep = (tri_idx[:, 0] != tri_idx[:, 1]) & (tri_idx[:, 1] != tri_idx[:, 2]) & (tri_idx[:, 0] != tri_idx[:, 2])
    tri_idx = tri_idx[keep]
    assert len(uniq) < 65536
    parts[name] = {
        "min": [round(float(x), 6) for x in lo],
        "max": [round(float(x), 6) for x in hi],
        "vertexCount": int(len(uniq)),
        "indexCount": int(tri_idx.size),
        "positions": b64(uniq.astype("<i2")),
        "indices": b64(tri_idx.astype("<u2").reshape(-1)),
    }
    print(name, "verts", len(uniq), "tris", len(tri_idx), "dropped", int((~keep).sum()),
          "bbox", np.round(lo, 4), np.round(hi, 4), file=sys.stderr)

header = """/*!
 * Kachaka robot meshes, derived from pf-robotics/kachaka-api
 *   ros2/kachaka_description/meshes/kachaka/{body,left_tire,right_tire,solenoid}.stl
 *   https://github.com/pf-robotics/kachaka-api
 * Copyright 2023 Preferred Robotics, Inc. Licensed under the Apache License,
 * Version 2.0 (see src/assets/kachaka/LICENSE).
 * Modifications: converted from binary STL to quantized int16 positions and
 * uint16 triangle indices (base64), with the URDF visual origins applied and
 * the frame converted from ROS (x fwd, y left, z up) to three.js (x fwd, y up, z right).
 * Generated by tools/kachaka_stl_to_js.py - do not edit by hand.
 */
"""
with open(OUT, "w") as f:
    f.write(header)
    f.write("export const KACHAKA_MESHES = ")
    f.write(json.dumps(parts, indent=1))
    f.write(";\n")
