// Precompute the strategy-lab results that ship with the demo (src/js/phase_3/labDefaults.js),
// so the report opens instantly; the page can re-run the same experiments with other settings.
// usage: npm install && npm run lab
import { build } from "esbuild";
import { writeFile, mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const src = path.join(root, "src");
const out = path.join(src, "js/phase_3/labDefaults.js");

const vendoredThree = {
  name: "vendored-three",
  setup(b) {
    b.onResolve({ filter: /^three$/ }, () => ({ path: path.join(src, "vendor/three/three.module.min.js") }));
    b.onResolve({ filter: /^three\/addons\// }, (args) => ({
      path: path.join(src, "vendor/three/addons", args.path.slice("three/addons/".length)),
    }));
  },
};

// the 3D objects paint a few canvas textures (signs, screens); nothing is drawn here
const any = new Proxy(function () {}, {
  get: (_, p) => (p === Symbol.toPrimitive ? () => 0 : p === "then" ? undefined : any),
  apply: () => any,
  set: () => true,
});
globalThis.document = { createElement: () => ({ width: 0, height: 0, style: {}, getContext: () => any }) };

const bundle = await build({
  entryPoints: [path.join(src, "js/phase_3/lab.js")],
  bundle: true,
  format: "esm",
  platform: "node",
  target: "node20",
  write: false,
  plugins: [vendoredThree],
});
const dir = await mkdtemp(path.join(tmpdir(), "kachaka-lab-"));
const file = path.join(dir, "lab.mjs");
await writeFile(file, bundle.outputFiles[0].text);
const { runLab } = await import(pathToFileURL(file).href);

let last = -1;
const res = await runLab({
  onProgress: (p, cfg, seed) => {
    const pct = Math.floor(p * 20) * 5;
    if (pct !== last) console.log(`${String(pct).padStart(3)}%  ${cfg.key} seed ${seed}`);
    last = pct;
  },
});
await rm(dir, { recursive: true, force: true });

const header = "// Generated by tools/run_lab.mjs (npm run lab) - do not edit by hand.\n// Strategy-lab results for the scripted morning in lab.js with the default settings.\n";
await writeFile(out, `${header}export const LAB_DEFAULTS = ${JSON.stringify(res)};\n`);
console.log(`wrote ${path.relative(root, out)} in ${(res.ms / 1000).toFixed(1)} s`);
const f = (v, d = 1) => (v === null || v === undefined ? "  -  " : v.toFixed(d));
for (const c of Object.values(res.configs)) {
  const m = c.mean;
  console.log(
    `${c.key.padEnd(12)} n=${c.robots} ${c.strategy.padEnd(10)} done=${f(m.done)} wait=${f(m.avgWaitMin)}m p1=${f(m.p1Min)}m [${f(c.min.p1Min)}-${f(c.max.p1Min)}] rides=${f(m.rides)} km=${f(m.km, 2)} util=${f(m.utilization * 100, 0)}% waitShare=${f(m.waitShare * 100, 0)}% queued=${f(m.queued)}`,
  );
}
